# Generated by Django 4.2.6 on 2024-08-22 06:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseModel",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="quiz.basemodel",
                    ),
                ),
                ("category_name", models.CharField(max_length=200)),
            ],
            bases=("quiz.basemodel",),
        ),
        migrations.CreateModel(
            name="Main_field",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="quiz.basemodel",
                    ),
                ),
                ("Field_name", models.CharField(max_length=200)),
            ],
            bases=("quiz.basemodel",),
        ),
        migrations.CreateModel(
            name="Sub_category",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="quiz.basemodel",
                    ),
                ),
                ("sub_cat_name", models.CharField(max_length=200)),
                (
                    "main_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.category"
                    ),
                ),
            ],
            bases=("quiz.basemodel",),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="quiz.basemodel",
                    ),
                ),
                ("Question", models.CharField(max_length=500)),
                (
                    "Level",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        max_length=50,
                    ),
                ),
                ("marks", models.IntegerField()),
                (
                    "main_field_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.main_field",
                    ),
                ),
                (
                    "ques_sub",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.sub_category",
                    ),
                ),
            ],
            bases=("quiz.basemodel",),
        ),
        migrations.AddField(
            model_name="category",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field",
                to="quiz.main_field",
            ),
        ),
        migrations.CreateModel(
            name="Answers",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="quiz.basemodel",
                    ),
                ),
                ("answer", models.CharField(max_length=250)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question_Ans",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.question"
                    ),
                ),
            ],
            bases=("quiz.basemodel",),
        ),
    ]
