# Generated by Django 4.2.6 on 2024-08-22 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_category_main_field_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="main_field_name",
        ),
    ]
