# Generated by Django 4.2.6 on 2024-08-22 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0004_remove_category_main_field_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quiz.main_field"
            ),
        ),
    ]
