# Generated by Django 4.2.6 on 2024-08-22 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0005_alter_category_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="main_field_name",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.main_field",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="field",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field",
                to="quiz.main_field",
            ),
        ),
    ]
