# Generated by Django 4.2.6 on 2024-08-22 07:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0006_category_main_field_name_alter_category_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="field",
        ),
    ]
